
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 03 13:56:52 CEST 2020
//----------------------------------------------------

package batiste;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int MAKECIRCLE = 8;
  public static final int FRAME = 7;
  public static final int WORD = 25;
  public static final int PLUS = 17;
  public static final int EQUAL = 21;
  public static final int MAKEPOLYGON = 4;
  public static final int POINT = 26;
  public static final int MAKERECT = 5;
  public static final int MAKECONT = 12;
  public static final int ID = 24;
  public static final int QUOTE = 15;
  public static final int CONTAINERSTART = 10;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int MAKECONTAINER = 6;
  public static final int MAKEANIMATETRANSFORM = 9;
  public static final int MAKELINE = 3;
  public static final int MINUS = 19;
  public static final int SEP = 13;
  public static final int error = 1;
  public static final int MAKETEXT = 14;
  public static final int CONTAINERSTOP = 11;
  public static final int INTEGER = 23;
  public static final int TERM = 2;
  public static final int MAKEANIMATION = 16;
  public static final int UMINUS = 22;
}

